<a href="https://colab.research.google.com/github/FernandaSouza4602/Desafio-2---IA-MACHINE-LEARNING-2024/blob/main/Desafio2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
base_dados = pd.read_csv ('/content/drive/MyDrive/UNIFAA/wine-dataset.csv', encoding = 'utf-8')

In [34]:
base_dados = base_dados.drop(base_dados.index[1])
base_dados

Wine Alcohol Malic Acid   Ash Alcalinity of ash Magnesium Total phenols  \
2       1   14.23       1.71  2.43              15.6       127          2.80   
5       1   14.37       1.95  2.50              16.8       113          3.85   
6       1   13.24       2.59  2.87              21.0       118          2.80   
7       1   14.20       1.76  2.45              15.2       112          3.27   
8       1   14.39       1.87  2.45              14.6        96          2.50   
..    ...     ...        ...   ...               ...       ...           ...   
175     3   13.71       5.65  2.45              20.5        95          1.68   
176     3   13.40       3.91  2.48              23.0       102          1.80   
177     3   13.27       4.28  2.26              20.0       120          1.59   
178     3   13.17       2.59  2.37              20.0       120          1.65   
179     3   14.13       4.10  2.74              24.5        96          2.05   

    Flavanoids Nonflavanoid phenols Proanthocyanins Color intensity    Hue  \
2         3.06                 0.28            2.29            5.64  1.040   
5         3.49                 0.24            2.18             7.8  0.860   
6         2.69                 0.39            1.82            4.32  1.040   
7         3.39                 0.34            1.97            6.75  1.050   
8         2.52                 0.30            1.98            5.25  1.020   
..         ...                  ...             ...             ...    ...   
175       0.61                 0.52            1.06             7.7  0.640   
176       0.75                 0.43            1.41             7.3  0.700   
177       0.69                 0.43            1.35            10.2  0.590   
178       0.68                 0.53            1.46             9.3  0.600   
179       0.76                 0.56            1.35             9.2  0.610   

    OD280/OD315 of diluted wines Proline  
2                           3.92    1065  
5                           3.45    1480  
6                           2.93     735  
7                           2.85    1450  
8                           3.58    1290  
..                           ...     ...  
175                         1.74     740  
176                         1.56     750  
177                         1.56     835  
178                         1.62     840  
179                         1.60     560  

[176 rows x 14 columns]

In [35]:
dados = base_dados.drop(columns=['Wine'])
alvo = base_dados['Wine']

In [44]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
alvo = le.fit_transform(alvo)
alvo

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [45]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(dados, alvo, test_size=0.20, random_state=42)

In [46]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dense(64, activation=tf.nn.relu),
    tf.keras.layers.Dense(4, activation=tf.nn.softmax)
])

model.compile(optimizer=tf.keras.optimizers.Adam(),
              loss='sparse_categorical_crossentropy',
              metrics=['Accuracy'])

model.fit(x_train, y_train, epochs=50)



Epoch 1/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - Accuracy: 0.3254 - loss: 1.3496
Epoch 2/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - Accuracy: 0.7073 - loss: 1.1603 
Epoch 3/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.8996 - loss: 0.9914 
Epoch 4/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9395 - loss: 0.8402 
Epoch 5/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9410 - loss: 0.6836 
Epoch 6/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - Accuracy: 0.9582 - loss: 0.5425 
Epoch 7/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.9378 - loss: 0.4405 
Epoch 8/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.9566 - loss: 0.3286 
Epoch 9/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.9813 - loss: 0.2609 
Epoch 10/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.9735 - loss: 0.2111 
Epoch 11/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.9787 - loss: 0.1615 
Epoch 12/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.9813 - loss: 0.1436 
Ep

In [47]:
model.evaluate(x_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - Accuracy: 0.9711 - loss: 0.0655  


[0.06342503428459167, 0.9722222089767456]

In [48]:
import numpy as np
from sklearn.metrics import confusion_matrix

previsoes_prob = model.predict(x_test)

previsoes = np.argmax(previsoes_prob, axis=1)

matrix = confusion_matrix(y_test, previsoes)

print(matrix)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[[14  0  0]
 [ 1 13  0]
 [ 0  0  8]]
